[2023-10-15 22:16:16 +0800] [30028] [INFO] Starting gunicorn 21.2.0
[2023-10-15 22:16:16 +0800] [30028] [INFO] Listening at: http://127.0.0.1:8080 (30028)
[2023-10-15 22:16:16 +0800] [30028] [INFO] Using worker: gevent
[2023-10-15 22:16:16 +0800] [30031] [INFO] Booting worker with pid: 30031
[2023-10-15 22:16:16 +0800] [30032] [INFO] Booting worker with pid: 30032
[2023-10-15 22:16:16 +0800] [30033] [INFO] Booting worker with pid: 30033
[2023-10-15 22:16:55 +0800] [30028] [INFO] Handling signal: int
[2023-10-15 14:16:55 +0000] [30033] [INFO] Worker exiting (pid: 30033)
[2023-10-15 14:16:55 +0000] [30032] [INFO] Worker exiting (pid: 30032)
[2023-10-15 14:16:55 +0000] [30031] [INFO] Worker exiting (pid: 30031)
[2023-10-15 22:16:55 +0800] [30028] [INFO] Shutting down: Master
[2023-10-15 22:16:57 +0800] [30152] [INFO] Starting gunicorn 21.2.0
[2023-10-15 22:16:57 +0800] [30152] [INFO] Listening at: http://127.0.0.1:8080 (30152)
[2023-10-15 22:16:57 +0800] [30152] [INFO] Using worker: gevent
[2023-10-15 22:16:57 +0800] [30168] [INFO] Booting worker with pid: 30168
[2023-10-15 22:16:57 +0800] [30169] [INFO] Booting worker with pid: 30169
[2023-10-15 22:16:57 +0800] [30170] [INFO] Booting worker with pid: 30170
[2023-10-15 22:26:10 +0800] [30152] [INFO] Handling signal: term
[2023-10-15 22:26:10 +0800] [30622] [INFO] Starting gunicorn 21.2.0
[2023-10-15 22:26:10 +0800] [30622] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2023-10-15 22:26:10 +0800] [30622] [ERROR] Retrying in 1 second.
[2023-10-15 14:26:10 +0000] [30168] [INFO] Worker exiting (pid: 30168)
[2023-10-15 14:26:10 +0000] [30169] [INFO] Worker exiting (pid: 30169)
[2023-10-15 14:26:10 +0000] [30170] [INFO] Worker exiting (pid: 30170)
[2023-10-15 22:26:11 +0800] [30152] [INFO] Shutting down: Master
[2023-10-15 22:26:11 +0800] [30622] [INFO] Listening at: http://127.0.0.1:8080 (30622)
[2023-10-15 22:26:11 +0800] [30622] [INFO] Using worker: gevent
[2023-10-15 22:26:11 +0800] [30647] [INFO] Booting worker with pid: 30647
[2023-10-15 22:26:11 +0800] [30648] [INFO] Booting worker with pid: 30648
[2023-10-15 22:26:11 +0800] [30649] [INFO] Booting worker with pid: 30649
[2023-10-15 22:42:12 +0800] [30622] [INFO] Handling signal: term
[2023-10-15 22:42:12 +0800] [31574] [INFO] Starting gunicorn 21.2.0
[2023-10-15 22:42:12 +0800] [31574] [ERROR] Connection in use: ('127.0.0.1', 8080)
[2023-10-15 22:42:12 +0800] [31574] [ERROR] Retrying in 1 second.
[2023-10-15 14:42:12 +0000] [30647] [INFO] Worker exiting (pid: 30647)
[2023-10-15 14:42:12 +0000] [30648] [INFO] Worker exiting (pid: 30648)
[2023-10-15 14:42:12 +0000] [30649] [INFO] Worker exiting (pid: 30649)
[2023-10-15 22:42:13 +0800] [30622] [INFO] Shutting down: Master
[2023-10-15 22:42:13 +0800] [31574] [INFO] Listening at: http://127.0.0.1:8080 (31574)
[2023-10-15 22:42:13 +0800] [31574] [INFO] Using worker: gevent
[2023-10-15 22:42:13 +0800] [31596] [INFO] Booting worker with pid: 31596
[2023-10-15 22:42:13 +0800] [31597] [INFO] Booting worker with pid: 31597
[2023-10-15 22:42:13 +0800] [31598] [INFO] Booting worker with pid: 31598
[2023-10-15 22:42:13 +0800] [31596] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'buysms.wsgii'
[2023-10-15 22:42:13 +0800] [31596] [INFO] Worker exiting (pid: 31596)
[2023-10-15 22:42:14 +0800] [31574] [ERROR] Worker (pid:31596) exited with code 3
[2023-10-15 22:42:14 +0800] [31598] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'buysms.wsgii'
[2023-10-15 22:42:14 +0800] [31598] [INFO] Worker exiting (pid: 31598)
[2023-10-15 22:42:14 +0800] [31597] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/ggevent.py", line 147, in init_process
    super().init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'buysms.wsgii'
[2023-10-15 22:42:14 +0800] [31597] [INFO] Worker exiting (pid: 31597)
[2023-10-15 22:42:14 +0800] [31574] [ERROR] Worker (pid:31597) exited with code 3
